config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :product do
    resources :base, only: :index
    resources :solars
    resources :batteries
    resources :charge_controllers
    resources :grid_ties
    resources :pv_inverter_pumps
  end

  resources :products, only: [] do
    resources :inventory_line_items, only: :index
    resources :inventory_invoice_line_items, only: :index
  end

  resources :inventory_invoice_line_items, only: [] do
    resources :inventory_line_items, only: :index
  end

  resources :addresses
  resources :configurations
  resources :branches
  resources :users
  resources :inventory_invoices

  root  'home#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :branch
  belongs_to :user
end

app/models/branch.rb
class Branch < ActiveRecord::Base

  has_one :address
  has_many :users
  has_many :inventory_invoices

  accepts_nested_attributes_for :address, allow_destroy: true

  delegate :home_number, :street, :group, :quartier, :district, :city, :country, :branch_id, to: :address

  def to_s
    name.split.map(&:capitalize)*' '
  end
end

app/models/inventory_invoice.rb
class InventoryInvoice < ActiveRecord::Base
  has_many :inventory_invoice_line_items
  belongs_to :user
  belongs_to :branch

  accepts_nested_attributes_for :inventory_invoice_line_items

  validates :shipping_cost, :vat, :other_cost, :date, :branch, :user, presence: true

end

app/models/inventory_invoice_line_item.rb
class InventoryInvoiceLineItem < ActiveRecord::Base

  has_many :inventory_line_items
  belongs_to :product, class_name: "Product::Base"
  belongs_to :inventory_invoice

  validates :product, :quantity, :unit_price, :final_unit_price, presence: true
  validate :final_unit_price_is_greater_than_unit_price

  before_validation :add_inventory_line_items, on: :create

  private

  def final_unit_price_is_greater_than_unit_price
    errors.add(:final_unit_price, :greater_than_or_equal_to_unit_price) if final_unit_price? && unit_price? && final_unit_price < unit_price
  end

  def add_inventory_line_items
    return unless quantity?
    inventory_line_items.clear
    quantity.times do
      inventory_line_item = inventory_line_items.build(inventory_invoice_line_item: self)
      inventory_line_item.product = product
      inventory_line_item.unit_price = unit_price
      inventory_line_item.final_unit_price = final_unit_price
    end
  end

end

app/models/inventory_line_item.rb
class InventoryLineItem < ActiveRecord::Base
  belongs_to :inventory_invoice_line_item
  belongs_to :product, class_name: "Product::Base"

  validates :product, :inventory_invoice_line_item, :unit_price, :final_unit_price, :state, presence: true

  def self.in_stock
    where(state: "in_stock")
  end

  def self.group_by_product_and_unit_price
    group(:product_id, :unit_price).count
  end

end

app/models/product/base.rb
class Product::Base < ActiveRecord::Base
  self.table_name = :products
  TYPES = ["Product::Solar", "Product::Battery", "Product::ChargeController", "Product::GridTie", "Product::PvInverterPump"]

  has_many :inventory_invoice_line_items, foreign_key: "product_id"
  has_many :inventory_line_items, foreign_key: "product_id"
           InventoryLineItem
  validates_lengths_from_database
  validates :name, presence: true

  def self.types
    TYPES.map(&:constantize)
  end

  def stock
    inventory_line_items.in_stock.count
  end

  def unit_price
    inventory_line_items.in_stock.average(:unit_price)
  end

  def final_unit_price
    inventory_line_items.in_stock.average(:final_unit_price)
  end

  def to_s
    name
  end
end

app/models/product/battery.rb
class Product::Battery < Product::Base
  validates :voltage, :current, presence: true
end

app/models/product/solar.rb
class Product::Solar < Product::Base
  validates :power_rating, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  has_one :address
  has_many :inventory_invoices

  belongs_to :branch

  accepts_nested_attributes_for :address

  validates :name, :branch, :phone, :email, presence: true

  delegate :home_number,:street,:group,:quartier,:district,:city,:country, to: :address

  def to_s
    " #{name} "
  end

  private

  def password_required?
    !persisted? || !password.blank? || !password_confirmation.blank?
  end

  def email_required?
    false
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  inherit_resources
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  actions :all, except: :show
  def new
    @branch = Branch.new
    @branch.build_address
    super
  end

  def index
    @grid = BranchesGrid.new(params[:branches_grid]) do |scope|
      collection.page(params[:page]).per_page(10)
    end
  end

  private
  def permitted_params
    params.permit( branch: [:name, address_attributes: [:id, :home_number, :street,:group,:quartier,:district,:city, :country]])
  end
end

app/controllers/configurations_controller.rb
class ConfigurationsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @branch = Branch.find(current_user.branch_id)
    @user = User.where(branch_id: @branch.id)
    @inventory = InventoryInvoice.where(branch_id: @branch.id)
  end
end

app/controllers/inventory_invoice_line_items_controller.rb
class InventoryInvoiceLineItemsController < ApplicationController
  belongs_to :product, parent_class: Product::Base
end

app/controllers/inventory_invoices_controller.rb
class InventoryInvoicesController < ApplicationController
  actions :all, except: [:show]
  def new
    @inventory_invoice = current_user.inventory_invoices.build
    @inventory_invoice.inventory_invoice_line_items.build
    super
  end

  def index
    @grid = InventoryInvoicesGrid.new(params[:users_grid]) do |scope|
      scope.page(params[:page]).per_page(10).decorate
    end
  end

  private
  def permitted_params
    params.permit(
      inventory_invoice: [
        :shipping_cost, :vat, :other_cost, :number, :date, :user_id, :branch_id,
        {
          inventory_invoice_line_items_attributes: [ :product_id, :quantity, :unit_price, :final_unit_price]
        }
      ]
    )
  end
end

app/controllers/inventory_line_items_controller.rb
class InventoryLineItemsController < ApplicationController
  belongs_to :product, parent_class: Product::Base, :polymorphic => true
  belongs_to :inventory_invoice_line_item, :polymorphic => true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product::Base.all
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  actions :all, except: :show
  def new
    @user = User.new
    @user.build_address
  end

  def index
    @grid = UsersGrid.new(params[:users_grid]) do |scope|
      scope.page(params[:page]).per_page(10)
    end
  end

  private
  def permitted_params
    params.permit(user: [:name, :email, :password, :phone,:confirm_password, :branch_id, :admin, address_attributes:[:id, :home_number, :street, :group, :quartier, :district, :city, :country]])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title
    t page_title_translation_key,
      page_title_context.merge(:default => :"title.default")
  end

  def page_title_translation_key
    :"title.#{controller_name}.#{action_name}"
  end

  def page_title_context
    controller.view_assigns.symbolize_keys
  end
end

app/helpers/branch_helper.rb
module BranchHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.slim
.row
  .col-md-12
    h1.page-header
      =@branch.to_s
      small
        =current_user.to_s
.row
  .col-md-3
    .panel.panel-primary
      .panel-heading
        .row
          .col-md-3
            .fa.fa-th-large.fa-5x
          .col-md-9.text-right
            .huge 29
            div Customers

  .col-md-3
    .panel.panel-primary
      .panel-heading
        .row
          .col-md-3
            .fa.fa-cubes.fa-5x
          .col-md-9.text-right
            .huge = @inventory.count
            div Products
  .col-md-3
    .panel.panel-primary
      .panel-heading
        .row
          .col-md-3
            .fa.fa-shopping-cart.fa-5x
          .col-md-9.text-right
            .huge 390
            div Producs been sold
  .col-md-3
    .panel.panel-primary
      .panel-heading
        .row
          .col-md-3
            .fa.fa-group.fa-5x
          .col-md-9.text-right
            .huge
              ="#{@user.count}"
            div Users
.row
  .col-md-6
    .panel.panel-default
      .panel-heading
        .fa.fa-bar-chart-o.fa-fw
        | All product
        .pull-right
          .btn-group
            .btn.btn-default.btn-xs.dropdown-toggle data-toggle="dropdown"
              | Action
              .caret
            ul.dropdown-menu.pull-right
              li
                a href="#home" New
      .panel-body
        .row
          .col-md-12
            table.table.table-bordered
              thead
                tr
                  th Number
                  th Shipping Cost
                  th Vat
                  th Other Cost
                  th Date
                  th Create By
                  th
                    .pull-right Actions
              tbody
                -@branch.inventory_invoices.each do |ii|
                  tr
                    td
                      =ii.number
                    td
                      =ii.shipping_cost
                    td
                      =ii.vat
                    td
                      =ii.other_cost
                    td
                      =ii.date
                    td
                      =ii.user
                    td
                      .pull-right
                        =link_to(fa_icon("trash"), inventory_invoice_path(ii), method: :delete, data: { confirm: "Are you sure to delete this ?"} , class: " btn btn-default btn-xs")
  .col-md-6
    .panel.panel-default
      .panel-heading
        .fa.fa-bar-chart-o.fa-fw
        | All product
        .pull-right
          .btn-group
            .btn.btn-default.btn-xs.dropdown-toggle data-toggle="dropdown"
              | Action
              .caret
            ul.dropdown-menu.pull-right
              li
                a href="#home" New

app/views/inventory_invoice_line_items/index.html.slim
table.table.table-bordered
  thead
    tr
      th Product
      th Quantity
      th Unit Price
      th Inventory
  tbody#inventory
  -collection.each do |inventory_line_item|
    tr
      td=link_to inventory_line_item.product.name, polymorphic_path(inventory_line_item.product)
      td=inventory_line_item.quantity
      td=inventory_line_item.unit_price
      td=link_to "Inventory", inventory_invoice_line_item_inventory_line_items_path(inventory_line_item)

app/views/inventory_invoices/_form.html.slim
.row
  .col-md-12
    =simple_nested_form_for(resource) do |f|
      =f.error_notification
      =f.input :user_id, as: :hidden, input_html: { value: current_user.id }
      =f.input :branch_id, as: :hidden, input_html: { value: current_user.branch_id }
      .row
        .col-md-4
          =f.input :number
        .col-md-4
          =f.input :date, as: :date_picker, input_html: {"data-date-format" => "DD-MM-YYYY"}
      =f.simple_fields_for(:inventory_invoice_line_items) do |line_item_fields|
        .row
          .col-md-3
            =line_item_fields.association :product
          .col-md-3
            =line_item_fields.input :quantity
          .col-md-3
            =line_item_fields.input :unit_price
          .col-md-3
            =line_item_fields.input :final_unit_price
            =line_item_fields.link_to_remove "Remove", class: "btn btn-xs btn-danger pull-right", style: " margin-top: -12px;"
      .row
        .col-md-12
            =f.link_to_add "Add more inventory", :inventory_invoice_line_items, class: "btn btn-info btn-xs"
      .row
        .col-md-4
          =f.input :shipping_cost
        .col-md-4
          =f.input :vat
        .col-md-4
          =f.input :other_cost
          .btn-toolbar
            .btn-group
              =f.submit class: "btn btn-primary"
            .btn-group
              = link_to t('.back'), :back, class: "btn btn-default"

app/views/inventory_invoices/edit.html.slim
.row
  .col-md-6
    h4.page-header Edit
.row
  .col-md-6
    =render "form"

app/views/inventory_invoices/index.html.slim
.row
  .col-md-12
    h3.page-header= page_title
    .pull-right.button-on-table
      =link_to I18n.t("actions.new"), new_inventory_invoice_path, class: "btn btn-sm btn-default"
    =datagrid_table(@grid, html:{class: 'table'})

app/views/inventory_invoices/new.html.slim
.row
  .col-md-8
    h4.page-header= page_title
    =render "form"

app/views/inventory_line_items/index.html.slim
table.table.table-bordered
  thead
    tr
      th Product
      th Unit Price
      th Amount

  tbody#inventory
  -collection.group_by_product_and_unit_price.each do |key, value|
    tr
      td=key.first
      td=key.last
      td=value

app/views/users/_form.html.slim
=simple_form_for(resource) do |f|
  .row
    .col-md-12
      =f.input :name
  .row
    .col-md-3
      =f.input :email
    .col-md-3
      =f.input :phone
    .col-md-3
      =f.association :branch
    .col-md-3
      =f.input :admin, as: :switch_boolean
  - if action_name == 'new' || 'create'
    .row
      .col-md-6
        =f.input :password, required: true
      .col-md-6
        =f.input :password_confirmation, required: true
  h4.page-header= t('Address')
  .row
    =f.simple_fields_for :address do |address|
      .col-md-2
        =address.input :home_number
      .col-md-2
        =address.input :street
      .col-md-2
        =address.input :group
      .col-md-2
        =address.input :quartier
      .col-md-2
        =address.input :district
      .col-md-2
        =address.input :city

  .row
    .col-md-12
      .btn-toolbar
        .btn-group
          =f.submit class: "btn btn-primary"
        .btn-group
          = link_to "Back", users_path, class: "btn btn-default"
javascript:
  $(".switch-boolean").bootstrapSwitch();

app/views/users/edit.html.slim
.row
  .col-md-12
    h1.page-header
      =page_title
    =render "form"

app/views/users/index.html.slim
.row
  .col-md-12
    h3.page-header
      =page_title
      .pull-right.button-on-table
        =link_to t('.new'), new_user_path, class: "btn btn-default btn-sm"
    =datagrid_table(@grid, html:{class: 'table'})

app/views/users/new.html.slim
.row
  .col-md-12
    h1.page-header
      =page_title
    =render "form"

app/views/users/show.html.slim
=resource.name