config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :product do
    resources :base, only: :index
    resources :solars
    resources :batteries
    resources :charge_controllers
    resources :grid_ties
    resources :pv_inverter_pumps
  end

  resources :products, only: [] do
    resources :inventory_line_items, only: :index
    resources :inventory_invoice_line_items, only: :index
  end

  resources :inventory_invoice_line_items, only: [] do
    resources :inventory_line_items, only: :index
  end

  resources :addresses
  resources :configurations
  resources :branches
  resources :users
  resources :inventory_invoices

  root  'home#index'

end

app/models/product/base.rb
class Product::Base < ActiveRecord::Base
  self.table_name = :products
  TYPES = ["Product::Solar", "Product::Battery", "Product::ChargeController", "Product::GridTie", "Product::PvInverterPump"]

  has_many :inventory_invoice_line_items, foreign_key: "product_id"
  has_many :inventory_line_items, foreign_key: "product_id"
           InventoryLineItem
  validates_lengths_from_database
  validates :name, presence: true

  def self.types
    TYPES.map(&:constantize)
  end

  def stock
    inventory_line_items.in_stock.count
  end

  def unit_price
    inventory_line_items.in_stock.average(:unit_price)
  end

  def final_unit_price
    inventory_line_items.in_stock.average(:final_unit_price)
  end

  def to_s
    name
  end
end

app/models/product/battery.rb
class Product::Battery < Product::Base
  validates :voltage, :current, presence: true
end

app/models/product/charge_controller.rb
class Product::ChargeController < Product::Base
  validates :current, presence: true
end

app/models/product/grid_tie.rb
class Product::GridTie < Product::Base
  
end

app/models/product/pv_inverter_pump.rb
class Product::PvInverterPump < Product::Base
  
end

app/models/product/solar.rb
class Product::Solar < Product::Base
  validates :power_rating, presence: true
end

app/controllers/product/base_controller.rb
class Product::BaseController < ApplicationController
  actions :all

  private
  def permitted_params
    params.permit( resource_request_name => [:name, :description, :power_rating, :voltage, :current] )
  end
end

app/controllers/product/batteries_controller.rb
class Product::BatteriesController < Product::BaseController
  defaults resource_class: Product::Battery
end

app/controllers/product/charge_controllers_controller.rb
class Product::ChargeControllersController < Product::BaseController
  defaults resource_class: Product::ChargeController
end

app/controllers/product/grid_ties_controller.rb
class Product::GridTiesController < Product::BaseController
  defaults resource_class: Product::GridTie
end

app/controllers/product/pv_inverter_pumps_controller.rb
class Product::PvInverterPumpsController < Product::BaseController
  defaults resource_class: Product::PvInverterPump
end

app/controllers/product/solars_controller.rb
class Product::SolarsController < Product::BaseController
  defaults resource_class: Product::Solar
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product::Base.all
  end

end

app/views/product/base/edit.html.slim
.row
  .col-md-6
    h1.page-header
      =page_title
    =render "form"

app/views/product/base/index.html.slim
.row
  .col-md-12
    h3.page-header
      =page_title
      .pull-right
        -if collection.model_name.human == Product::Base.model_name.human
          .btn-group
            button.btn.btn-default.btn-sm.dropdown-toggle#dropdown_product data-toggle="dropdown" = I18n.t("actions.new")
            ul.dropdown-menu.pull-right aria-labelledby="dropdown_product"
              -Product::Base.types.each do |type|
                li = link_to type.model_name.human, new_polymorphic_path(type)
        -else
          =link_to t('.new'), new_polymorphic_path(collection.klass), class: "btn btn-default btn-sm"
    table.table.table-bordered
      thead
        tr
          th
            =t'.number'
          th
            =t'.name'
          th
            =t('.type')
          th
            =t('.description')
          th
            =t('.stock')
          th Inventory
          th Inventory line items
          th
            =t('.unit_price')
          th
            =t('.final_unit_price')
          th
            =t('.action')
      tbody#product_list
      -collection.each do |product|
        tr
          td=product.id
          td=link_to product.name, polymorphic_path(product)
          td=product.class.model_name.human
          td=product.description
          td=product.stock
          td=link_to "Inventory", product_inventory_line_items_path(product)
          td=link_to "Inventory Line Item", product_inventory_invoice_line_items_path(product)
          td=product.unit_price
          td=product.final_unit_price
          td
            .btn-group
              =link_to fa_icon("pencil-square"), edit_polymorphic_path(product), class: " btn btn-default btn-xs "
              =link_to fa_icon("trash"), polymorphic_path(product), method: :delete, data: { confirm: "Are you sure to delete this ?"} , class: " btn btn-default btn-xs "

app/views/product/base/new.html.slim
.row
  .col-md-6
    h1.page-header
      =page_title
    =render "form"

app/views/product/base/show.html.slim
.row
  .col-md-6
    h1.page-header
      =page_title
    =render "show"